set @KIM_TYP_ID_S = 10000;
set @ROLE_ID_S = 10000;
set @RSP_ID_S = 10000;
set @ATTR_DATA_ID_S = 10000;
set @ROLE_RSP_ID_S = 10000;
set @ROLE_RSP_ACTN_ID_S = 10000;

-- CREATE KIM TYPE
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR) 
  VALUES ('Y', @KIM_TYP_ID_S, 'Derived Role: Parent Group Type', 'KR-SYS', UUID(), 'parentGroupDerivedRoleService', 1)
;
-- CREATE LEAVE APPROVER ROLE
INSERT INTO KRIM_ROLE_T (ROLE_ID, OBJ_ID, VER_NBR, ROLE_NM, NMSPC_CD, KIM_TYP_ID, ACTV_IND,LAST_UPDT_DT)
  VALUES(@ROLE_ID_S, UUID(), 1, 'Leave Approver Role', 'KR-SYS', @KIM_TYP_ID_S, 'Y', SYSDATE())
;
-- CREATE LEAVE APPROVER RESPONSIBILITY
INSERT INTO KRIM_RSP_T (RSP_ID, OBJ_ID, VER_NBR, RSP_TMPL_ID, NMSPC_CD, NM, DESC_TXT, ACTV_IND )
VALUES  (@RSP_ID_S, UUID(), 1, 1, 'KR-SYS', 'Line Manager', 'Responsibility for Line Manager', 'Y')
;
-- CREATE LINE MANAGER RESPONSIBILITY ATTRIBUTE DEFINITIONS
INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID, OBJ_ID, VER_NBR, RSP_ID, KIM_TYP_ID, KIM_ATTR_DEFN_ID, ATTR_VAL)
VALUES  (@ATTR_DATA_ID_S, UUID(), 1, @RSP_ID_S, 7,  41, 'false')
;
set @ATTR_DATA_ID_S = @ATTR_DATA_ID_S + 1;
INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID, OBJ_ID, VER_NBR, RSP_ID, KIM_TYP_ID, KIM_ATTR_DEFN_ID, ATTR_VAL)
VALUES  (@ATTR_DATA_ID_S, UUID(), 1, @RSP_ID_S, 7,  16, 'Line Manager Node')
;
set @ATTR_DATA_ID_S = @ATTR_DATA_ID_S + 1;
INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID, OBJ_ID, VER_NBR, RSP_ID, KIM_TYP_ID, KIM_ATTR_DEFN_ID, ATTR_VAL)
VALUES  (@ATTR_DATA_ID_S, UUID(), 1, @RSP_ID_S, 7,  13, 'LeaveApplicationDocumentType')
;
set @ATTR_DATA_ID_S = @ATTR_DATA_ID_S + 1;
INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID, OBJ_ID, VER_NBR, RSP_ID, KIM_TYP_ID, KIM_ATTR_DEFN_ID, ATTR_VAL)
VALUES  (@ATTR_DATA_ID_S, UUID(), 1, @RSP_ID_S, 7,  40, 'false')
;
-- LINK LINE MANAGER RESPONSIBILITY TO "LEAVE APPROVER" ROLE
INSERT INTO KRIM_ROLE_RSP_T (ROLE_RSP_ID, OBJ_ID, VER_NBR, ROLE_ID, RSP_ID, ACTV_IND) 
VALUES (@ROLE_RSP_ID_S, UUID(), 1, @ROLE_ID_S, @RSP_ID_S, 'Y')
;
-- ADD ACTION APPROVE TYPE
INSERT INTO KRIM_ROLE_RSP_ACTN_T (ROLE_RSP_ACTN_ID, OBJ_ID, VER_NBR, ACTN_TYP_CD, PRIORITY_NBR, ACTN_PLCY_CD, ROLE_MBR_ID, ROLE_RSP_ID, FRC_ACTN) 
VALUES (@ROLE_RSP_ACTN_ID_S, UUID(), 1,'A', NULL, 'A', '*', @ROLE_RSP_ID_S, 'Y')
;
-- ------------------------------------------------------
-- CREATE SUB DEPARTMENT RESPONSIBILITY
set @RSP_ID_S = @RSP_ID_S + 1;
INSERT INTO KRIM_RSP_T (RSP_ID, OBJ_ID, VER_NBR, RSP_TMPL_ID, NMSPC_CD, NM, DESC_TXT, ACTV_IND )
VALUES  (@RSP_ID_S, UUID(), 1, 1, 'KR-SYS', 'Sub Department Manager', 'Responsibility for Sub Department Manager', 'Y')
;
-- CREATE LINE MANAGER RESPONSIBILITY ATTRIBUTE DEFINITIONS
set @ATTR_DATA_ID_S = @ATTR_DATA_ID_S + 1;
INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID, OBJ_ID, VER_NBR, RSP_ID, KIM_TYP_ID, KIM_ATTR_DEFN_ID, ATTR_VAL)
VALUES  (@ATTR_DATA_ID_S, UUID(), 1, @RSP_ID_S, 7,  41, 'false')
;
set @ATTR_DATA_ID_S = @ATTR_DATA_ID_S + 1;
INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID, OBJ_ID, VER_NBR, RSP_ID, KIM_TYP_ID, KIM_ATTR_DEFN_ID, ATTR_VAL)
VALUES  (@ATTR_DATA_ID_S, UUID(), 1, @RSP_ID_S, 7,  16, 'Sub Department Manager Node')
;
set @ATTR_DATA_ID_S = @ATTR_DATA_ID_S + 1;
INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID, OBJ_ID, VER_NBR, RSP_ID, KIM_TYP_ID, KIM_ATTR_DEFN_ID, ATTR_VAL)
VALUES  (@ATTR_DATA_ID_S, UUID(), 1, @RSP_ID_S, 7,  13, 'LeaveApplicationDocumentType')
;
set @ATTR_DATA_ID_S = @ATTR_DATA_ID_S + 1;
INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID, OBJ_ID, VER_NBR, RSP_ID, KIM_TYP_ID, KIM_ATTR_DEFN_ID, ATTR_VAL)
VALUES  (@ATTR_DATA_ID_S, UUID(), 1, @RSP_ID_S, 7,  40, 'false')
;
-- LINK SUB DEPARTMENT MANAGER RESPONSIBILITY TO "LEAVE APPROVER" ROLE
set @ROLE_RSP_ID_S = @ROLE_RSP_ID_S + 1;
INSERT INTO KRIM_ROLE_RSP_T (ROLE_RSP_ID, OBJ_ID, VER_NBR, ROLE_ID, RSP_ID, ACTV_IND) 
VALUES (@ROLE_RSP_ID_S, UUID(), 1, @ROLE_ID_S, @RSP_ID_S, 'Y')
;
-- ADD ACTION APPROVE TYPE
set @ROLE_RSP_ACTN_ID_S = @ROLE_RSP_ACTN_ID_S  + 1;
INSERT INTO KRIM_ROLE_RSP_ACTN_T (ROLE_RSP_ACTN_ID, OBJ_ID, VER_NBR, ACTN_TYP_CD, PRIORITY_NBR, ACTN_PLCY_CD, ROLE_MBR_ID, ROLE_RSP_ID, FRC_ACTN) 
VALUES (@ROLE_RSP_ACTN_ID_S, UUID(), 1,'A', NULL, 'A', '*', @ROLE_RSP_ID_S, 'Y')
;
-- ---------------------------------------------------------------
-- CREATE KIM TYPE
set @KIM_TYP_ID_S = @KIM_TYP_ID_S + 1;
INSERT INTO KRIM_TYP_T (ACTV_IND,KIM_TYP_ID,NM,NMSPC_CD,OBJ_ID,SRVC_NM,VER_NBR) 
  VALUES ('Y', @KIM_TYP_ID_S, 'Derived Role: Leave Notification Type', 'KR-SYS', UUID(), 'leaveNotificationDerivedRoleService', 1)
;
-- CREATE LEAVE NOTIFICATION ROLE
set @ROLE_ID_S = @ROLE_ID_S + 1;
INSERT INTO KRIM_ROLE_T (ROLE_ID, OBJ_ID, VER_NBR, ROLE_NM, NMSPC_CD, KIM_TYP_ID, ACTV_IND,LAST_UPDT_DT)
  VALUES(@ROLE_ID_S, UUID(), 1, 'Leave Notification Role', 'KR-SYS', @KIM_TYP_ID_S, 'Y', SYSDATE())
;
-- CREATE LEAVE NOTIFICATION RESPONSIBILITY
set @RSP_ID_S = @RSP_ID_S + 1;
INSERT INTO KRIM_RSP_T (RSP_ID, OBJ_ID, VER_NBR, RSP_TMPL_ID, NMSPC_CD, NM, DESC_TXT, ACTV_IND )
VALUES  (@RSP_ID_S, UUID(), 1, 1, 'KR-SYS', 'Leave Notification', 'Responsibility for Leave Notification', 'Y')
;
-- CREATE LEAVE NOTIFICATION RESPONSIBILITY ATTRIBUTE DEFINITIONS
set @ATTR_DATA_ID_S = @ATTR_DATA_ID_S + 1;
INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID, OBJ_ID, VER_NBR, RSP_ID, KIM_TYP_ID, KIM_ATTR_DEFN_ID, ATTR_VAL)
VALUES  (@ATTR_DATA_ID_S, UUID(), 1, @RSP_ID_S, 7,  41, 'false')
;
set @ATTR_DATA_ID_S = @ATTR_DATA_ID_S + 1;
INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID, OBJ_ID, VER_NBR, RSP_ID, KIM_TYP_ID, KIM_ATTR_DEFN_ID, ATTR_VAL)
VALUES  (@ATTR_DATA_ID_S, UUID(), 1, @RSP_ID_S, 7,  16, 'Notification Node')
;
set @ATTR_DATA_ID_S = @ATTR_DATA_ID_S + 1;
INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID, OBJ_ID, VER_NBR, RSP_ID, KIM_TYP_ID, KIM_ATTR_DEFN_ID, ATTR_VAL)
VALUES  (@ATTR_DATA_ID_S, UUID(), 1, @RSP_ID_S, 7,  13, 'LeaveApplicationDocumentType')
;
set @ATTR_DATA_ID_S = @ATTR_DATA_ID_S + 1;
INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID, OBJ_ID, VER_NBR, RSP_ID, KIM_TYP_ID, KIM_ATTR_DEFN_ID, ATTR_VAL)
VALUES  (@ATTR_DATA_ID_S, UUID(), 1, @RSP_ID_S, 7,  40, 'false')
;
-- LINK LEAVE NOTIFICATION RESPONSIBILITY TO "LEAVE NOTIFICATION" ROLE
set @ROLE_RSP_ID_S = @ROLE_RSP_ID_S + 1;
INSERT INTO KRIM_ROLE_RSP_T (ROLE_RSP_ID, OBJ_ID, VER_NBR, ROLE_ID, RSP_ID, ACTV_IND) 
VALUES (@ROLE_RSP_ID_S, UUID(), 1, @ROLE_ID_S, @RSP_ID_S, 'Y')
;
-- ADD ACTION FYI TYPE
set @ROLE_RSP_ACTN_ID_S = @ROLE_RSP_ACTN_ID_S + 1;
INSERT INTO KRIM_ROLE_RSP_ACTN_T (ROLE_RSP_ACTN_ID, OBJ_ID, VER_NBR, ACTN_TYP_CD, PRIORITY_NBR, ACTN_PLCY_CD, ROLE_MBR_ID, ROLE_RSP_ID, FRC_ACTN) 
VALUES (@ROLE_RSP_ACTN_ID_S, UUID(), 1,'F', NULL, 'A', '*', @ROLE_RSP_ID_S, 'Y')
;
-- ----------------------------------------------------
-- CREATE BACKUP ROLE
set @ROLE_ID_S = @ROLE_ID_S + 1;
INSERT INTO KRIM_ROLE_T (ROLE_ID, OBJ_ID, VER_NBR, ROLE_NM, NMSPC_CD, KIM_TYP_ID, ACTV_IND,LAST_UPDT_DT)
  VALUES(@ROLE_ID_S, UUID(), 1, 'Backup Role', 'KR-SYS', (select kim_typ_id from krim_typ_t where nm = 'Derived Role: Principal'), 'Y', SYSDATE())
;
-- CREATE LEAVE APPROVER RESPONSIBILITY
set @RSP_ID_S = @RSP_ID_S + 1;
INSERT INTO KRIM_RSP_T (RSP_ID, OBJ_ID, VER_NBR, RSP_TMPL_ID, NMSPC_CD, NM, DESC_TXT, ACTV_IND )
VALUES  (@RSP_ID_S, UUID(), 1, 1, 'KR-SYS', 'Backup', 'Responsibility for Backup', 'Y')
;
-- CREATE LINE MANAGER RESPONSIBILITY ATTRIBUTE DEFINITIONS
set @ATTR_DATA_ID_S = @ATTR_DATA_ID_S + 1;
INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID, OBJ_ID, VER_NBR, RSP_ID, KIM_TYP_ID, KIM_ATTR_DEFN_ID, ATTR_VAL)
VALUES  (@ATTR_DATA_ID_S, UUID(), 1, @RSP_ID_S, 7,  41, 'false')
;
set @ATTR_DATA_ID_S = @ATTR_DATA_ID_S + 1;
INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID, OBJ_ID, VER_NBR, RSP_ID, KIM_TYP_ID, KIM_ATTR_DEFN_ID, ATTR_VAL)
VALUES  (@ATTR_DATA_ID_S, UUID(), 1, @RSP_ID_S, 7,  16, 'Delegator Node')
;
set @ATTR_DATA_ID_S = @ATTR_DATA_ID_S + 1;
INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID, OBJ_ID, VER_NBR, RSP_ID, KIM_TYP_ID, KIM_ATTR_DEFN_ID, ATTR_VAL)
VALUES  (@ATTR_DATA_ID_S, UUID(), 1, @RSP_ID_S, 7,  13, 'LeaveApplicationDocumentType')
;
set @ATTR_DATA_ID_S = @ATTR_DATA_ID_S + 1;
INSERT INTO KRIM_RSP_ATTR_DATA_T (ATTR_DATA_ID, OBJ_ID, VER_NBR, RSP_ID, KIM_TYP_ID, KIM_ATTR_DEFN_ID, ATTR_VAL)
VALUES  (@ATTR_DATA_ID_S, UUID(), 1, @RSP_ID_S, 7,  40, 'false')
;
-- LINK BACKUP RESPONSIBILITY TO "BACKUP" ROLE
set @ROLE_RSP_ID_S = @ROLE_RSP_ID_S + 1;
INSERT INTO KRIM_ROLE_RSP_T (ROLE_RSP_ID, OBJ_ID, VER_NBR, ROLE_ID, RSP_ID, ACTV_IND) 
VALUES (@ROLE_RSP_ID_S, UUID(), 1, @ROLE_ID_S, @RSP_ID_S, 'Y')
;
-- ADD ACTION APPROVE TYPE
set @ROLE_RSP_ACTN_ID_S = @ROLE_RSP_ACTN_ID_S + 1;
INSERT INTO KRIM_ROLE_RSP_ACTN_T (ROLE_RSP_ACTN_ID, OBJ_ID, VER_NBR, ACTN_TYP_CD, PRIORITY_NBR, ACTN_PLCY_CD, ROLE_MBR_ID, ROLE_RSP_ID, FRC_ACTN) 
VALUES (@ROLE_RSP_ACTN_ID_S, UUID(), 1,'A', NULL, 'A', '*', @ROLE_RSP_ID_S, 'Y')
;